server:
  port: 3000
  host: localhost

db:
  type: postgres
  host: localhost
  database: apitelemed
  username: postgres
  password: adm123
  port: 5432
  synchronize: true
  migrationsRun: false
  logging: true

graphql:
  playground: true
  degub: true