db:
  type: postgres
  host: localhost
  database: ldtidata
  username: postgres
  password: postgres
  port: 5432
  synchronize: true
  migrationsRun: false
  logging: true

graphql:
  playground: true
  degub: true